version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      -"80:80"

  app:
    build: 
      context: ./spotify-stats-backend
    ports:
      -"3000:3000"

  nginx:
    build: 
      context: ./nginx
    ports:
      -"80:80"
    depends_on:
      - frontend
      - app

  redis:
    image: redis:latest
    ports:
      -"6379:6379"